# docker-compose file to run test(s) using dockerized Postgresql
# Start Postgres from root of project with following command:
#     sudo docker-compose -f scripts/compose.postgres.test.yml up -d
# Stop Postgres from root of project with following command:
#     sudo docker-compose -f scripts/compose.postgres.test.yml down
version: '2'
services:
  postgres:
    image: postgres:9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=guble
    volumes:
      - /tmp/guble_test_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
