# docker compose file to run a test postgresql
# start db with from root of project with following command:
# sudo docker-compose -f scripts/postgres.test.compose.yml up -d
version: '2'
services:
  postgres:
    image: postgres:9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=guble
    volumes:
      - /tmp/guble_test_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
